var rules = [
    "V=a,e,i,o,u",
    "L=a:,e:,i:,o:,u:",
    "W=ə,ɛ,ɪ,ɔ,ʊ",
    "N=ãẽĩõũ",
    "X=a,e,i,o,u,ə,ɛ,ɪ,ɔ,ʊ",
    "P=ptkbdg",
    "B=tʃ,dʒ,ts,dz",
    ";bdfghjklmnprstw",
    "C=bdfghjklmnprstwʒɸʃ",
    "A=tʃ,dʒ,ts,dz,ʎ,ɲ,ʃ,ʒ",
    "T=k,g,t,d,l,n,s,z",
    ";TO MARK STRESS USE ACUTE ACCENT",
    ";TO CONVERT RHOTICS",
    "rr/y",
    "r/ɾ/_/#_",
    "y/r",
    ";Final E Neutralization:",
    "e/ə/_#",
    ";Velar nasal shift",
    "ng//_#",
    "ng/k/#_",
    "ng/n",
    ";U dropping",
    "u//P_P",
    ";Geminated affrication",
    "kk/tʃ",
    "tt/ts",
    "pp/ɸ",
    ";Final stop unclustering",
    "VPP1/:P1/_#",
    "PP1/P1/_#",
    ";Labiodental fricative lenition",
    "f/h",
    ";Aspiration",
    "Ph/Pʰ",
    ";Great final consonant shift",
    "j/ʒ/_#",
    "p/ɸ/_#",
    "k/j/_#",
    "s/ʃ/_#",
    "t/s/_#",
    "l/w/_#",
    "ɾ/l/_#",
    ";Intervocalic S and W voicing",
    "s/z/X_X",
    "w/v/X_ə#",
    "v/ɸ",
    ";Nasalization",
    ";{an,en,in,on,un}/{ã,ẽ,ĩ,õ,ũ}/_{C,#}/_{j,w}",
    ";{am,em,im,om,um}/{ãw,ẽw,ĩw,õw,ũw}/_#",
    ";so we have nli is ni",
    "Vn/N/_{C,#}/_{li,j,w}",
    "Vm/Nw/_#",
    ";Final shcwa dropping",
    "ə/y/#_#",
    "ə//_#/#C_",
    "y/ə",
    ";Rhoticization",
    "z/ɾ/_#",
    ";Intervocalic-stop-voicing (COMMENTED FOR NEW ORTHOGRAPHY)",
    ";{p,t,k}/{b,d,g}/{V,á,í}_{V,N,á,í,j}",
    "{p,t,k}/{b,d,g}/u_{V,á,í}",
    ";Plosive declustering",
    "VPP1/V:P1",
    "PP1/P1",
    ";Vowel lengthening",
    "V/V:/_{h,ɸ}",
    "h//V:_",
    ";Palatalization",
    "T/A/_{i,i:,ĩ,j,í}",
    "j//A_",
    "{i,í}/i:/A_/_:",
    "{dʒ,dz}/{tʃ,ts}/_#",
    "s//_{s,ʃ}",
    "i://A_{V,N}",
    ";Yeismo",
    "ʎi:/j/{V,á,í}_/_{V,j}",
    "ʎ/j",
    "ji:/j/{V,L}_/_{V,L}",
    "{ij,i:j}/ej",
    "{ji,ji:}/i:",
    "://_:",
    ";Clustered H drop",
    "h//_/#_",
    ";tl palatalization",
    "tl/j",
    ";L into tap",
    "l/ɾ/{ptkm}_",
    "l//C_X/XC_",
    ";Nasal gemination (ALLOPHONIC)",
    ";{P,m}/n/_n",
    ";{P,m}/m/_m",
    ";{P,m}//_ɲ",
    ";Nasal vowel diphthongization",
    "N/Nj̃/_V",
    "i//Nj̃_",
    ";Denasalization",
    "Nj̃/V:j",
    ";s rhotic (ALLOPHONE)",
    "sɾ/r",
    ";Approximants resolution",
    "j//_j",
    "w//_w",
    ";j/jɣ/_w (ALLOPHONE)",
    ";Vowel shift",
    "V/W/_/_:",
    "á/a",
    "í/ɛ",
    "L/V",
    ";Hiatus to diphthong resolution",
    "əX/X",
    "X1X1/X1",
    "{a,e,ɛ}{a,e,i,ɛ,ɪ}/əɪ̯",
    "{o,ɔ}{i,ɪ}/əɪ̯",
    "{a,e,ɛ}{o,u,ɔ,ʊ}/əu̯",
    "{əɪ̯,əu̯}/ɨ",
    "{i,ɪ}/j/_X/Cɾ_",
    "{o,u,ɔ,ʊ}/w/_X/Cɾ_",
    "{wu,wʊ}/u",
    "{uw,ʊw}/u/_{C,#}",
    "ə//X_/CɾX_",
    ";Nasal hiatus diphthong resolution",
    "əN/N",
    "{a,ə}//_ã",
    "{e,ɛ}//_ẽ",
    "{i,ɪ}//_ĩ",
    "{o,ɔ}//_õ",
    "{u,ʊ}//_ũ",
    "{u,ʊ}/w̃/_N/Cɾ_",
    "Vẽ/N",
    "Wẽ/N",
    "{i,ɪ}/j̃/_N/Cɾ_",
    "{a,e,ɛ}{ã,ẽ,ĩ}/ɐ̃j̃",
    "{a,e,ɛ}{õ,ũ}/ɐ̃w̃",
    "{o,ɔ}/w̃/_N /Cɾ_",
    "{ɐ̃j̃,ɐ̃w̃}/ɨ̃",
    "{w̃ũ,ũw}/ũ",
    ";Syllabic nasal apparition",
    "{ɨ̃,ɨ}/n̩",
    ";Initial U dropping",
    "ʊ//#_{P,B}",
    ";Plosive fricativization",
    ";{b,d,g}/{β,ð,ɣ}/{X}_{V,X}",
    ";Final O shift",
    "ɔ/ʊ/_#",
    ";R to H",
    "r/h",
    ";jw resolution",
    "jw/ju/_{C,#}",
    ";Plosive-nasal allophones",
    ";{P,m}n/n:",
    ";{P,m}m/m:",
    ";{P,m}ɲ/ɲ:",
    "ɾ/r"
    ];